WalletConnect/walletconnect-utils

jsonrpc/provider/src/provider.ts
23b988cd5ffe2c89553f311fa66738a69202f2ef actually introduced the bug reported in https://github.com/WalletConnect/walletconnect-monorepo/issues/839 .
What I believe is happening is that 23b988cd5ffe2c89553f311fa66738a69202f2ef causes us to evade an existing error flow.   `@walletconnect/jsonrpc-provider` now re-emits the QR code closed error in https://github.com/WalletConnect/walletconnect-monorepo/blob/v1.0/packages%2Fhelpers%2Fsigner-connection%2Fsrc%2Findex.ts#L201 and `@walletconnect/ethereum-provider` does not have a listener specified for `error` so we are blowing up within `EventEmitter`.
Prior to 23b988cd5ffe2c89553f311fa66738a69202f2ef, the QR code being aborted would resolve as a rejection in https://github.com/WalletConnect/walletconnect-monorepo/blob/v1.0/packages%2Fhelpers%2F …
=> Undo 23b988cd5ffe2c89553f311fa66738a69202f2ef but keep naming

jsonrpc/utils/src/validators.ts, jsonrpc/utils/test/validators.test.ts
Fixes:
- https://github.com/WalletConnect/walletconnect-monorepo/issues/1106
- https://github.com/WalletConnect/walletconnect-monorepo/issues/558
When calling `isJsonRpcRequest` inside the `RELAYER_EVENTS.message` handler [here](https://github.com/WalletConnect/walletconnect-monorepo/blob/v2.0/packages/sign-client/src/controllers/engine.ts#L442), `payload` seems to occasionally decode to a non-object value such as  empty string `""` or `1` (why is another question I wasn't yet able to answer).
`isJsonRpcRequest` relies on `isJsonRpcPayload`, which allows `payload` as `any`, but assumes it can be operated on like an object.
This leads to invalid operations such as `"id" in ""`, resulting in the observed TypeError.
The bug could be reproduced by running the new test cases without the fix:
- …
=> fix(jsonrpc-utils): handle non-object payloads in `isJsonRpcPayload`

misc/logger/package.json, misc/logger/src/constants.ts, misc/logger/src/utils.ts
- Updated pino pretty version to `^7.6.0`
- Removed depricated `prettyPrint` configuration
=> refactor: bump pino pretty version

misc/relay-api/src/jsonrpc.ts
Restores the v1 `waku_` prefix for backwards compatibility
=> refactor: restores waku prefix for backwards compatibility

relay/relay-auth/package.json, relay/relay-auth/src/api.ts, relay/relay-auth/src/types.ts, relay/relay-auth/test/index.test.ts, relay/relay-auth/test/shared/values.ts
Update JWT payload with new params:
- aud -> url of target server (relayUrl)
- iat -> epoch when issued (seconds)
- exp -> epoch when expires (seconds
=> update JWT payload with new params

relay/relay-api/src/jsonrpc.ts
Added `irn_` prefix to the jsonrpc methods as per the [spec](https://github.com/WalletConnect/walletconnect-specs/issues/90)
=> feat: irn_ prefix

misc/keyvaluestorage/.gitignore, misc/keyvaluestorage/package.json, misc/keyvaluestorage/src/node-js/db.ts, misc/keyvaluestorage/src/node-js/index.ts, misc/keyvaluestorage/test/index.test.ts
Fix for the nodejs storage where the singleton implementation was not allowing the initialization of multiple persisted DBs.
The PR includes:
- fix for the said issue
- a test to make sure this scenario is covered
- tidying up the test dbs
=> fix: multiple persisted DBs

misc/logger/src/index.ts
PR to fix an issue where `pino` was not re-exported correctly thus making it unusable when imported from `@walletconnect/logger`
- fix default export `pino`
- fix exporting `Logger` type
`import  { pino } from "@walletconnect/logger";`
`import type { Logger } from "@walletconnect/logger";`
Canary release: `@walletconnect/logger@2.0.0-rc-be5347f3`
dogfooding in monorepo & web-examples
=> fix: pino export

jsonrpc/ws-connection/src/ws.ts
@pedrouid 
When connection is lost parseConnectionError is throwing an error when using 'ws' lib:
```
Uncaught TypeError: Cannot read property 'message' of undefined
``` 
This exception is causing that the app is not reconnecting after connection is lost.
The problem that if found is that in `event` that is casted on `socket.onerror`, the field `error` is undefined.
To fix that I create an Error object based on `errorEvent.message` on parseError call when `errorEvent.error` is undefined.
This will fix reconnect scenario when using `ws`.
Let me know if I missed something or theres anything that I did not consider to fix it! :)
see:
https://github.com/WalletConnect/walletconnect-utils/issues/8
=> fix: parsing error on ws error event

jsonrpc/ws-connection/src/ws.ts, jsonrpc/ws-connection/test/index.test.ts, jsonrpc/ws-connection/test/shared/values.ts, misc/logger/src/index.ts
Builds on top of #18. Fixes #8.
The event returned by the browser `WebSocket` implementation is generic/does not contain an `error` or `message` key. We return a generic error with the attempted URL in this case.
See my comment here for deeper context: https://github.com/WalletConnect/walletconnect-utils/pull/18#issuecomment-1323644463
Also:
* Adds test suite for `jsonrpc-ws-connection` with basic sanity checks. Can/should be expanded on later.
=> fix(ws): ensure we emit a meaningful error msg if `socket.onerror` returns none

jsonrpc/ws-connection/package.json, jsonrpc/ws-connection/test/index.test.ts, jsonrpc/ws-connection/test/shared/values.ts
Fix for ws tests to generate new auth before attempting to crease socket with relay similarly as in https://github.com/WalletConnect/walletconnect-utils/pull/39
That is needed because using a pre-built auth string fails as it has an expiry
=> fix: ws tests

jsonrpc/ws-connection/src/ws.ts, jsonrpc/ws-connection/test/index.test.ts, jsonrpc/ws-connection/test/shared/values.ts
Errors thrown in `ws` library such as `socket hang up` are not handled by the `WebSocket` api `onerror`. This was causing unhandled exceptions.
New error handling depending on the environment:
- In browser - `socket.onerror`
- in node - `socket.on('error')` 
Manual testing
Integration tests
Canary has been running this code for ~2 weeks
=> fix: ws error handler in node

jsonrpc/ws-connection/package.json
Added `events` as explicit dependency in `jsonrpc-ws-connection` as the package relies on it and throws `this.events.getMaxListeners is not a function` if it is not available during runtime
=> fix: events dependency

misc/heartbeat/src/heartbeat.ts, misc/heartbeat/src/types/heartbeat.ts
The interval is holding up the process from exiting during testing. This fix is probably one part of fixing the issue [#1507](https://github.com/WalletConnect/walletconnect-monorepo/issues/1507)
We found that this interval was lingering in tests using the package `wtfnode`.
=> feat: Implement a way to stop a heartbeat.

jsonrpc/provider/src/provider.ts, jsonrpc/ws-connection/src/ws.ts, jsonrpc/ws-connection/test/index.test.ts
- Towards https://github.com/WalletConnect/walletconnect-monorepo/issues/2091
- Forward the currently ignored `CloseEvent`
- Emit an error when an abnormal close is detected
- Unit tests
- Integrated downstream into `core` and tested regular WS conn and failure cases in React sample wallet via following canaries:
- `"@walletconnect/jsonrpc-ws-connection": "1.0.9-f14036a"`
- `"@walletconnect/jsonrpc-provider": "1.0.8-f37f36d"`
- `"@walletconnect/core": "2.4.9-ff902def"`
- Tested `provider.disconnect()` (close code `1005`)
- Tested `provider.transportClose()` (close code `1005`)
- Tested automatic relay rebalancing (close code `4010`)
=> feat(ws-connection): forward CloseEvent, adds test for useOnCloseEvent

browser/window-getters/package.json, browser/window-metadata/package.json, crypto/crypto/package.json, crypto/ecies-25519/package.json, crypto/randombytes/package.json, jsonrpc/http-connection/package.json, jsonrpc/provider/package.json, jsonrpc/types/package.json, jsonrpc/utils/package.json, jsonrpc/ws-connection/package.json, misc/cacao/package.json, misc/encoding/package.json, misc/environment/package.json, misc/events/package.json, misc/heartbeat/package.json, misc/keyvaluestorage/package.json, misc/logger/package.json, misc/safe-json/package.json, misc/time/package.json, relay/relay-api/package.json, relay/relay-auth/package.json
* Done via e.g. `npx lerna exec -- 'npm set-script prepublishOnly "npm run test && npm run build"'`
=> chore(scripts): adds publishing scripts to all pkgs

misc/did-jwt/package.json, package-lock.json
* Getting blocked on resolution errors for the multiformats import from `did-jwt` as dep both when running tests and in the Push next.js samples:
```
Error: Package subpath './bases/base58' is not defined by "exports" in /Users/bk/repos/walletconnect/push-client-js/node_modules/@walletconnect/did-jwt/node_modules/multiformats/package.json
❯ Object.<anonymous> ../../node_modules/@walletconnect/did-jwt/dist/cjs/did-jwt.js:5:18
```
- Turns out they moved to ESM-only publishing in v10.x.x (https://github.com/multiformats/js-multiformats/tags), which breaks any CJS-facing usage for us.
- Using `9.9.0` fixes the resolution issues, and we do not need any of the changes made in the higher major versions since we only use a single function `base58btc`
=> fix(did-jwt): use multiformats@9.9.0

jsonrpc/provider/src/provider.ts, jsonrpc/utils/src/format.ts, jsonrpc/utils/test/payloadId.test.ts, misc/safe-json/src/index.ts, misc/safe-json/test/index.test.ts
Implemented
- util fx to generate `bigint` rpc_id with 19 digits 
- default assigning bigint rpc_id in jsonrpc-provider (client -> server)
- custom JSON parser to handle `bigints` in safe-json 
- tests
After PR is approved we have to release the utils in order
1. safe-json
2. update jsonrpc-provider & jsonrpc-ws-connection with the released safe-json
3. release jsonrpc-provider & jsonrpc-ws-connection with the updated safe-json
=> feat: bigint rpc_id

misc/cacao/package-lock.json, misc/cacao/package.json
- Bump `isomorphic-unfetch` down to `3.1.0` since it does not depend on `unfetch@5.0.0` which [has an export bug](https://github.com/developit/unfetch/issues/162). `3.1.0` is also the version used in `@walletconnect/auth-client`.
=> Bump unfetch down due to export bug in 5.0.0

misc/did-jwt/package-lock.json, misc/did-jwt/package.json, misc/did-jwt/src/types.ts
* Required by: https://github.com/WalletConnect/walletconnect-docs/pull/583/
* Required for: https://github.com/WalletConnect/push-client-js/issues/5
* BREAKING CHANGE: this adds `act: string` as a required `JwtPayload` key
=> feat(types): adds act field to JwtPayload

misc/identity-keys/src/identity-keys.ts, misc/identity-keys/src/types.ts
- Add `getIdentityKey` to prevent having to call `resolveIdentity` to retrieve user's own identity key.
=> Add getter for identity key

misc/identity-keys/src/identity-keys.ts
- Unregister was using the old `${account}_identityKeys` which we changed to just be `${account}`, so updated it to new format
=> Fix unregister using old key format

misc/did-jwt/src/types.ts, misc/identity-keys/src/identity-keys.ts
- The storage key currently being created is missing the `:` colon at the end of the prefix, resulting in the key being `wc@2:identityKeys0.3//identityKeys` instead of `wc@2:identityKeys:0.3//identityKeys`
- Also: expands `JwtPayload` type to allow for `scp` (scope) parameter needed for Push JWTs
- Will merge via merge commit to preserve both independent commits
=> fix(storage): adds missing colon in `IDENTITY_KEYS_STORAGE_PREFIX`

misc/history/package-lock.json, misc/history/package.json, misc/history/src/utils.ts
- `@walletconnect/types@2.7.1` was being specified instead of being in line with others `@2.7.3`
- Caused TS errors: https://github.com/WalletConnect/walletconnect-utils/actions/runs/5121822955/jobs/9266156478#step:9:564
- Also: applied linter auto fixes
=> fix(history): aligns @walletconnect/types min version

misc/history/src/types.ts, misc/history/src/utils.ts, misc/history/test/history.test.ts
- Emit `RELAYER_EVENTS.message` to `relayer`, instead of "payload" to `provider`
- This is done because we do not need to acknowledge messages from history.
=> Fix relayer injection and add UT

jsonrpc/ws-connection/src/utils.ts, jsonrpc/ws-connection/src/ws.ts
- Sets up `truncateQuery` util, applied when logging connection string
- Comparison for generic error logs:
- Before: `WebSocket connection failed for URL: wss://relay.walletconnect.com?auth=...&projectId=...`
- After: `WebSocket connection failed for host: wss://relay.walletconnect.com`
- Also:
- Clean up helper fns into own `util` file
- This avoids unnecessarily detailed error logging, where the query params create unique errors in observability tooling, which are hard to dedupe.
- The query parameters do not provide useful debug info regarding misconfiguration, since we only log this error if the connection to the relay could not be made at all
- If the relay is reached, it returns a proper `3000` error code with a reason on the `close` event that can be used for debugging.
=> fix(ws-connection): truncate query string on error log

misc/did-jwt/package-lock.json, misc/did-jwt/package.json, misc/identity-keys/package-lock.json, misc/identity-keys/package.json
- Updates `multiformats` to latest on `did-jwt`
- bump `did-jwt` and `identity-keys`
=> chore(bump): bump did-jwt version that uses latest multiformats

misc/history/src/types.ts
- `originId` number -> string per [spec](https://docs.walletconnect.com/2.0/specs/servers/history/history-server-api#example)
=> Fix sending incorrect origin id

misc/identity-keys/src/identity-keys.ts
=> fix(identity-keys): ensure CACAO `domain` value is only the keyserver host

misc/identity-keys/package-lock.json, misc/identity-keys/package.json, misc/identity-keys/src/constants.ts, misc/identity-keys/src/identity-keys.ts, misc/identity-keys/src/types.ts
Make identity keys use domain of external dapp and accept a statement. 
Match the following specs: https://github.com/WalletConnect/walletconnect-specs/pull/138 and https://github.com/WalletConnect/walletconnect-specs/pull/139
=> Match identity key specs

misc/identity-keys/src/identity-keys.ts
- `unregisterIdentity` wasn't actually deleting the identity key after successful un-registration, now it does. 
This caused a bug in https://github.com/WalletConnect/notify-client-js/pull/60
=> fix: delete identity key after unregistering

jsonrpc/ws-connection/src/ws.ts
Overriding the origin header in the relay connection for RN.
Tested:
Relates to: https://github.com/WalletConnect/walletconnect-monorepo/pull/3847
=> feat: set origin header in react native

misc/identity-keys/CHANGELOG.md, misc/identity-keys/package.json, misc/identity-keys/src/identity-keys.ts, misc/identity-keys/src/types.ts, misc/identity-keys/test/identity-keys.test.ts, package-lock.json
- Refactor persist logic to defer persistence till after key server returns `200`
- Added check for signature validity  (not empty)
- Change access of `identityKeys.identityKeys` (the actual store) to be public 
- Add dev deps to allow successful testing on ci (fixex for circular dep)
Resolves https://github.com/WalletConnect/walletconnect-utils/issues/151
=> Fix identity key storing optimistically

misc/safe-json/src/index.ts, misc/safe-json/test/index.test.ts
- Updated regex to skip string literals when parsing
- Added logging on parsing fails
updated regex breakdown
```
(?<!"): Negative lookbehind assertion ensures that the match is not immediately preceded by a double quote (").
(?<=:): Positive lookbehind assertion ensures that the match is immediately preceded by a colon (:).
\b: Word boundary to ensure that the match is a whole word.
(\d{17,}|(?:[9](...))): Alternation for two possible patterns:
\d{17,}: Matches a sequence of at least 17 digits.
(?: ... ): Non-capturing group for a nested pattern.
[9](...): Matches the digit 9 followed by a nested pattern for specific numeric values.
(?=[,\}\]]|$): Positive lookahead assertion ensures that the match is immediately followed by either ,, }, ], or the end of the string.
=> fix: safe json parse

misc/did-jwt/src/types.ts, misc/identity-keys/CHANGELOG.md, misc/identity-keys/package-lock.json, misc/identity-keys/package.json, misc/identity-keys/src/identity-keys.ts, misc/identity-keys/src/types.ts, misc/identity-keys/test/identity-keys.test.ts, package-lock.json
- add `eip1271` support via `@walletconnect/cacao`
- Introduce **BREAKING CHANGE** where `signature` is no longer a `string` but instead a `CacaoSignature`
- Modify error message to showcase type of signature
- This is all in service of supporting eip1271 in notify client and thus Web3Inbox
- Bump major version to `2.0.0` since this is a breaking change
=> chore: add eip1271 support BREAKING CHANGE

misc/logger/CHANGELOG.md, misc/logger/package.json, misc/logger/src/serverChunkLogger.ts
> [!NOTE]
> Canary of this fix already published at: `@walletconnect/logger@2.1.2-98c4166`
- Resolves #166 
- Resolves https://github.com/WalletConnect/walletconnect-monorepo/issues/4414
- Clone a repro case here: https://github.com/WalletConnect/walletconnect-monorepo/issues/4414:
- Clone repo
- Upgrade to web3wallet `1.11.1` 
- Observe build failure
- Remove both references to `Writable`
- Maintain current API by instead satisfying Pino's `DestinationStream` interface
- Go back to repro case mentioned above
- Perform the following:
- First, add the following section to the package.sjon:
```json
"resolutions": {
"@walletconnect/logger": "2.1.2-98c4166"
},
```
- Then use `npm-force-resolutions` to force `@walletconnect/logger`'s canary to be fetched instead of the current latest
- Observe …
=> chore: do not extend writable, use destinationstream from pino

jsonrpc/http-connection/package.json, jsonrpc/provider/package.json, jsonrpc/types/package.json, misc/heartbeat/package.json, package-lock.json
- Relates to https://github.com/WalletConnect/walletconnect-monorepo/issues/4064
- Ensure that utils packages cannot transitively/implicitly resolve `events` package
=> fix(deps): ensure no transitive deps on `events` package

.github/workflows/ci.yml, jsonrpc/http-connection/package.json, jsonrpc/provider/package.json, jsonrpc/types/package.json, misc/heartbeat/package.json, misc/history/package.json, package-lock.json
Prep patch releases for 
-   `@walletconnect/heartbeat`
-   `@walletconnect/jsonrpc-types`
-   `@walletconnect/jsonrpc-provider`
-   `@walletconnect/jsonrpc-http-connection`
and removed `misc/history` from ci due to deprecation
=> chore: prep patch releases

jsonrpc/utils/src/format.ts, jsonrpc/utils/test/payloadId.test.ts
**Problem**
Current `payloadId` function has defects:
* It doesn't guarantee to return a unique value (due to Math.random() not being suited for cryptography and due to single-threadedness of javascript)
* It doesn't guarantee to always return a value greater than the previous one (since `Date.now()` can return the same value if called in the same tick)
**Solution 1**
Just use [`randomUUID()`](https://developer.mozilla.org/en-US/docs/Web/API/Crypto/randomUUID).
This breaks the expected return type of current `payloadId` which is a number
**Solution 2**
_Preserves function signature_
The most simple, performant and (in my opinion) sufficient solution would be the following:
```
export function getPayloadId(): number {
return crypto.getRandomValues(new Uint16Array(1))[0];
}
```
This would …
=> Improve payloadId generator

renovate.json
- Renovatebot PRs seem to have started failing on CI due to the root lockfile not being updated after internal `package.json` updates: https://github.com/WalletConnect/walletconnect-utils/actions/runs/9892262113/job/27324513410?pr=74#step:5:9
- Add `postUpdateOptions` which should ensure `npm install` is always run post deps update: https://docs.renovatebot.com/configuration-options/#postupdateoptions
- Reproduced the issue with a renovate branch locally and fixed via `npm install` in root dir
=> chore(config): ensure root lockfile is updated post-renovate update

jsonrpc/ws-connection/src/ws.ts
* Send bundleId/packageName in socket ops if the app is react-native
Related:
https://github.com/WalletConnect/walletconnect-monorepo/pull/5513
=> fix: send packageName or bundleId in socket opts for react native

jsonrpc/ws-connection/src/ws.ts
Removed packageName and bundleId headers for socket connections
=> fix: remove socket mobile headers

package-lock.json, relay/relay-auth/package.json
Reverts WalletConnect/walletconnect-utils#184
because build test of `relay-auth` break due to https://github.com/chaijs/chai/issues/1568
will be fixing it in another PR
=> Revert "fix: dedupe uint8arrays"

crypto/crypto/package.json, crypto/crypto/src/lib/fallback.ts, crypto/ecies-25519/package.json, crypto/ecies-25519/src/ecies/shared/index.ts, crypto/randombytes/package.json, crypto/randombytes/src/node/index.ts, jsonrpc/provider/test/index.test.ts, jsonrpc/ws-connection/test/index.test.ts, package-lock.json, relay/relay-auth/package.json, relay/relay-auth/src/api.ts
Based on https://github.com/WalletConnect/walletconnect-utils/pull/185, opened new PR due to conflicts in the initial PR
Replaced
- `aes-js` -> `@noble/ciphers`
- `hash.js` -> `@noble/hashes`
- `@stablelib/x25519` -> `@noble/curves`
- `@stablelib/ed25519` -> `@noble/curves`
- `randombytes` -> `@noble/hashes`
Canaries
- `@walletconnect/crypto@1.0.3-canary-bnl-1`
- `@walletconnect/ecies-25519@1.0.3-canary-bnl-1`
- `@walletconnect/randombytes@1.0.3-canary-bnl-1`
- `@walletconnect/relay-auth@1.0.4-canary-bnl-1`
=> refactor: replaced stablelib with noble libs

crypto/crypto/package.json, crypto/ecies-25519/package.json, crypto/randombytes/package.json, package-lock.json, relay/relay-auth/package.json
PR releasing utils
- @walletconnect/crypto@1.1.0
- @walletconnect/ecies-25519@1.1.0
- @walletconnect/randombytes@1.1.0
- @walletconnect/relay-auth@1.1.0
canaries deployments listed in https://github.com/WalletConnect/walletconnect-utils/pull/216
=> chore: releases utils

.github/workflows/publish-package.yml, .github/workflows/publish-pkg-canary.yml
**Description:**
This PR introduces a new GitHub Actions workflow (`.github/workflows/publish-package.yml`) to enable the manual publishing of individual packages as canary versions to npm. This provides a mechanism to release test versions of specific packages without needing a full `changeset`-based release across the monorepo.
**Changes:**
*   **New Workflow (`publish-package.yml`):**
*   Triggered manually via `workflow_dispatch`.
*   Accepts inputs for `branch`, `packageName` (npm name), `packageDir` (relative path), and `version`.
*   Checks out the specified branch.
*   Sets up Node.js v20 and installs dependencies using `npm ci`.
*   **Validates** that the provided `version` input string contains `-canary-`.
*   Uses `npm version` within the target package's directory to update …
=> feat(ci): add workflow for publishing single canary packages

.github/workflows/publish-pkg-canary.yml
Removed the explicit npm authentication step and replaced the environment variable from `NPM_TOKEN` to `NODE_AUTH_TOKEN`
=> fix(ci): update npm authentication method in canary publishing workflow

.github/workflows/publish-pkg-latest.yml
Supersedes #234 
This commit introduces a new GitHub Actions workflow for publishing packages to NPM with the 'latest' tag. 
The workflow, '.github/workflows/publish-pkg-latest.yml', is triggered manually via 'workflow_dispatch'. 
It publishes a specified package from the 'master' branch, using the version found in the package's 'package.json' file. This provides a standardized way to release production-ready versions of packages.
=> feat: add workflow for publishing latest npm packages

jsonrpc/provider/test/index.test.ts, jsonrpc/ws-connection/test/shared/values.ts
* The calls to deprecated staging.relay.walletconnect.com were no longer resolving.
* Replaced the staging WebSocket relay URL with the production URL in tests.
=> fix: update WebSocket relay URL to production endpoint

package.json
Removing "name" prop as unnecessary and inaccurate since this is a private monorepo workspace root package.json
=> chore: remove redundant package name from package.json
